include:
  - caddy/docker-compose.yaml

services:
  node-manager:
    image: ghcr.io/atominfra/node-manager:main
    restart: always
    ports:
      - 8000:8000
    environment:
      - CADDY_ADMIN_URL=http://caddy:2019
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
